services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: mmss
      RABBITMQ_DEFAULT_PASS: mmssmmnn
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - bridge

networks:
  bridge:
    external: true

volumes:
  rabbitmq_data:
