- name: Gerenciar código do projeto e serviços no servidor
  hosts: servers
  tasks:
    - name: Copiar código do projeto para o servidor
      ansible.builtin.copy:
        src: ~/aMosimann/aContabil/
        dest: /home/mosimann/aContabil/
        owner: mosimann
        group: mosimann
        mode: '0755'

    - name: Instalar dependências do Python no ambiente virtual
      ansible.builtin.pip:
        requirements: /home/mosimann/aContabil/requirements.txt
        virtualenv: /home/mosimann/aContabil/.venv
        virtualenv_command: /usr/bin/python3 -m venv
        state: present

    - name: Instalar ou atualizar Docker Compose v2
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        force: true

    - name: Reiniciar serviços Docker usando Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /home/mosimann/aContabil
        state: restarted
        pull: always
