---
- name: Deploy do Projeto aContabil
  hosts: all
  become: true
  tasks:
    # 1. Atualizar pacotes no servidor
    - name: Atualizar pacotes no servidor
      ansible.builtin.apt:
        update_cache: true

    # 2. Verificar e liberar travas do dpkg
    - name: Verificar existência de travas do apt/dpkg
      ansible.builtin.shell:
        cmd: |
          [ -f /var/lib/dpkg/lock-frontend ] && rm /var/lib/dpkg/lock-frontend
          [ -f /var/cache/apt/archives/lock ] && rm /var/cache/apt/archives/lock
          [ -f /var/lib/apt/lists/lock ] && rm /var/lib/apt/lists/lock
      changed_when: false

    # 3. Sincronizar arquivos do projeto
    - name: Sincronizar arquivos do projeto
      ansible.posix.synchronize:
        src: /home/jr/aMosimann/aContabil/
        dest: /home/mosimann/aContabil/
        delete: true
        rsync_opts:
          - "--archive"
          - "--compress"
          - "--verbose"

    # 4. Instalar Docker e Docker Compose
    - name: Instalar pacotes necessários (Docker e Docker Compose)
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
        state: present
        force: true

    # 5. Configurar permissões no projeto
    - name: Configurar permissões no projeto
      ansible.builtin.file:
        path: /home/mosimann/aContabil
        state: directory
        recurse: true
        owner: mosimann
        group: mosimann

    # 6. Garantir que os containers Docker estejam rodando
    - name: Iniciar containers com Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/mosimann/aContabil/
        state: present

    # 7. Reiniciar o Docker para aplicar mudanças (somente se necessário)
    - name: Reiniciar o Docker
      ansible.builtin.service:
        name: docker
        state: restarted
      when: docker_status.stdout != "active"
