---
- name: Test Docker container and Python environment
  hosts: mosimaxdev
  gather_facts: no

  tasks:
    - name: Execute raw command to check Python version in container
      raw: |
        docker exec mosimann-streamlit /bin/bash -c "source /aContabil/.venv/bin/activate && python --version"
      register: python_version_output
      ignore_errors: no

    - name: Show Python version output
      debug:
        msg: "{{ python_version_output.stdout | default('No Python version output') }}"
