---
- name: Deploy e configuração do projeto aContabil
  hosts: servidor_contabil
  become: true  # Executa como sudo
  vars:
    project_path: /home/mosimann/aContabil
    docker_compose_file: "{{ project_path }}/docker-compose.yml"
    python_version: "3.12"
    ssh_key_path: "~/.ssh/id_ed25519"

  tasks:
    - name: Atualizar pacotes do sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar pacotes necessários
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Garantir que o diretório do projeto existe
      file:
        path: "{{ project_path }}"
        state: directory
        owner: mosimann
        group: mosimann
        mode: '0755'

    - name: Copiar o arquivo docker-compose.yml para o servidor
      copy:
        src: ./docker-compose.yml
        dest: "{{ docker_compose_file }}"
        owner: mosimann
        group: mosimann
        mode: '0644'

    - name: Verificar se as imagens Docker existem
      shell: docker images --format '{{ "{{.Repository}}" }}:{{ "{{.Tag}}" }}' | grep -E 'amosimann-streamlit:latest|postgres:latest'
      register: docker_images
      failed_when: docker_images.rc != 0
      changed_when: false

    - name: Importar imagens Docker caso estejam ausentes
      block:
        - name: Verificar se a imagem do Streamlit está presente
          shell: docker images -q amosimann-streamlit:latest
          register: streamlit_image

        - name: Importar a imagem do Streamlit
          shell: docker load < ./amosimann-streamlit.tar
          when: streamlit_image.stdout == ""

        - name: Verificar se a imagem do PostgreSQL está presente
          shell: docker images -q postgres:latest
          register: postgres_image

        - name: Importar a imagem do PostgreSQL
          shell: docker load < ./mosimann-database.tar
          when: postgres_image.stdout == ""

    - name: Iniciar os serviços Docker usando docker-compose
      shell: docker-compose up -d
      args:
        chdir: "{{ project_path }}"
