name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          # Configurar chave SSH dentro do container, se necessário
          docker exec mosimann-streamlit /bin/bash -c "mkdir -p ~/.ssh && echo '${{ secrets.SERVER_KEY }}' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa"
          docker exec mosimann-streamlit /bin/bash -c "echo 'Host github.com\n\tStrictHostKeyChecking no\n' > ~/.ssh/config"
          
          # Clonar o repositório se ainda não existir
          docker exec mosimann-streamlit /bin/bash -c "if [ ! -d /aContabil/.git ]; then git clone git@github.com:gilberto-domingos/contabil.git /aContabil; fi"
          
          # Atualizar o repositório
          docker exec mosimann-streamlit /bin/bash -c "cd /aContabil && git pull origin main"

          # Reiniciar o container, se necessário (opcional)
          docker stop mosimann-streamlit

          docker start mosimann-streamlit
